Keras ocr onnx (#3)
* #2 keras_ocr 모델 layers.Permute 까지 진행

https://github.com/mukaman84/ocrSecurity/blob/85d6f74a78941676449bf0816dd8fec4dce84fc0/keras_ocr/recognition.py#L204

* #2 ~stn network

x= keras.layers.Lambda(_transform,
                           output_shape=stn_input_output_shape)([x, localization_net(x)]) 에서 막히는중

* #2 stn network lambda layer

x= keras.layers.Lambda(_transform,
                           output_shape=stn_input_output_shape)([x, localization_net(x)]) 레이어에서 미지원 함수로 에러남. 
node lambda/AddN of type AddN cannot be converted, fall back to tf2onnx
Traceback (most recent call last):
  File "build_model.py", line 66, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/main.py", line 60, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 794, in parse_graph
    graph, keras_node_dict, topo, top_level, output_names)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 595, in _parse_graph_core
    _on_parsing_tf_subgraph(graph, nodes, varset)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 335, in _on_parsing_tf_subgraph
    raise RuntimeError("Some tensorflow operation doesn't support, stop converting.")
RuntimeError: Some tensorflow operation doesn't support, stop converting.

* #2 stn onnx 성공, trt 실패

stn 네트워크까지 onnx는 변환되는데 trt는 안됨. 이런 에러 뜸
[2020-02-29 12:51:30   ERROR] (Unnamed Layer* 272) [Matrix Multiply]: only activation types allowed as input to this layer.
[2020-02-29 12:51:30   ERROR] (Unnamed Layer* 272) [Matrix Multiply]: only activation types allowed as input to this layer.
[2020-02-29 12:51:30   ERROR] (Unnamed Layer* 272) [Matrix Multiply]: only activation types allowed as input to this layer.
[2020-02-29 12:51:30   ERROR] (Unnamed Layer* 272) [Matrix Multiply]: only activation types allowed as input to this layer.
[2020-02-29 12:51:30   ERROR] (Unnamed Layer* 272) [Matrix Multiply]: only activation types allowed as input to this layer.
[2020-02-29 12:51:30   ERROR] (Unnamed Layer* 272) [Matrix Multiply]: only activation types allowed as input to this layer.
[2020-02-29 12:51:30   ERROR] (Unnamed Layer* 272) [Matrix Multiply]: only activation types allowed as input to this layer.
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)

* #2 recognizer 변환 완료, stn 네트워크 변환O, prediction_model 변환 X

* #2 clean